'use strict';
(()=>{
const data=window.MANUAL_DATA,main=document.querySelector('main');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hex=(n,w=2)=>Number(n).toString(16).toUpperCase().padStart(w,'0');
const kinds={official:'公式',undocumented:'非公式',alias:'別名',ignored:'接頭辞無視',unused:'未使用'};
const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const title=(h,p)=>`<h1>${h}</h1><p class="lead">${p}</p>`;
const state={query:'',family:'',kind:'',page:0,id:'BASE-00'};
const size=48;
function matches(i,q){
 const norm=s=>s.toUpperCase().replace(/[\s,]/g,'');
 if(norm(`${i.mnemonic} ${i.id} ${i.action} ${i.tokens.join(' ')}`).includes(norm(q)))return true;
 const b=q.replace(/\s/g,'').toUpperCase();
 return /^(?:[0-9A-F]{2})+$/.test(b)&&i.tokens.length*2===b.length&&i.tokens.every((t,j)=>/^(n|d|e|lo|hi)$/.test(t)||t===b.slice(j*2,j*2+2));
}
function reference(id){
 if(data.instructions.some(i=>i.id===id))state.id=id;
 main.innerHTML=title('機械語リファレンス','7ファミリ・1,780エンコーディング。命令名、機械語、動作から検索できます。')+
 `<div class="toolbar"><label>命令・バイト列・動作<input id="search" type="search" placeholder="例: LD A / DD CB / 3E42 / 加算" value="${esc(state.query)}"></label><label>ファミリ<select id="family"><option value="">すべて</option>${data.families.map(f=>`<option ${state.family===f?'selected':''}>${f}</option>`).join('')}</select></label><label>分類<select id="kind"><option value="">すべて</option>${Object.entries(kinds).map(([k,v])=>`<option value="${k}" ${state.kind===k?'selected':''}>${v}</option>`).join('')}</select></label><button id="reset">解除</button></div><p id="count" class="status" aria-live="polite"></p><div class="reference"><div class="list-column"><div id="list" class="list" aria-label="命令検索結果"></div><div class="pager"><button id="prev">前へ</button><span id="page"></span><button id="next">次へ</button></div></div><section id="detail" class="detail" aria-label="命令詳細"></section></div><details><summary>表記・接頭辞・フラグの読み方</summary><p>数値は16進数（時間・バイト数は10進数）。n=8bit即値、lo hi=16bit即値の下位→上位、d/e=符号付き8bit変位。JRのeは命令直後のPCから数えます。</p><p>S=符号、Z=ゼロ、H=半桁上り、P/V=パリティまたは符号付きoverflow、N=減算、C=桁上り。—は保持。偶数パリティは1のbit数が偶数のとき1。Y/Xは非公式のbit5/3です。</p><p>CB/DD/ED/FDはBASE命令ではなく接頭辞。DD/FDの連続では最後の指定が有効、EDの前のDD/FDは対象を変えません。任意長の接頭辞列は一覧に展開せず、標準形と1個のDD/FD形を収録しています。T-statesはWAITなし。リピート命令は1反復分です。</p><p>別名と未使用EDを含む1,780件は、異なる機能の数や外部oracleの検証件数ではありません。<a href="#sources">精度・検証範囲</a></p></details>`;
 for(const [selector,key] of [['#search','query'],['#family','family'],['#kind','kind']])main.querySelector(selector).addEventListener(selector==='#search'?'input':'change',e=>{state[key]=e.target.value;state.page=0;list();});
 main.querySelector('#reset').onclick=()=>{Object.assign(state,{query:'',family:'',kind:'',page:0});reference(state.id);};
 main.querySelector('#prev').onclick=()=>{state.page--;list();};main.querySelector('#next').onclick=()=>{state.page++;list();};
 list();detail();
}
function list(){
 const found=data.instructions.filter(i=>(!state.family||i.family===state.family)&&(!state.kind||i.classification===state.kind)&&matches(i,state.query));
 const pages=Math.max(1,Math.ceil(found.length/size));state.page=Math.max(0,Math.min(state.page,pages-1));
 main.querySelector('#count').textContent=`${found.length.toLocaleString()} / 1,780 件 · 詳細は命令を選択`;
 const el=main.querySelector('#list');el.innerHTML=found.slice(state.page*size,(state.page+1)*size).map(i=>`<button class="row" data-id="${i.id}" aria-pressed="${i.id===state.id}"><span class="opcode mono">${i.tokens.join(' ')}</span><span class="mono">${esc(i.mnemonic)}</span></button>`).join('')||'<p class="empty">一致する命令はありません。検索語や絞り込みを変更してください。</p>';
 el.scrollTop=0;el.querySelectorAll('button').forEach(b=>b.onclick=()=>{location.hash='reference/'+b.dataset.id;});
 main.querySelector('#page').textContent=`${state.page+1} / ${pages}`;
 main.querySelector('#prev').disabled=state.page===0;main.querySelector('#next').disabled=state.page===pages-1;
}
function value(k,v){return typeof v==='boolean'?String(v):typeof v==='number'?hex(v,['pc','sp','ix','iy','wz'].includes(k)?4:2)+'h':String(v);}
function detail(){
 const i=data.instructions.find(i=>i.id===state.id),e=i.example;
 const changes=Object.keys(e.before).filter(k=>e.before[k]!==e.after[k]);
 main.querySelector('#detail').innerHTML=`<p class="status">${i.id} · ${kinds[i.classification]||esc(i.classification)}</p><h2>${esc(i.mnemonic)}</h2><div class="encoding">${i.tokens.join(' ')}</div><div class="metrics"><div><span>長さ</span>${i.length} bytes</div><div><span>T-states</span>${esc(i.timing)}</div><div><span>ファミリ</span>${i.family}</div></div><p>${esc(i.action)}</p><h3>フラグ</h3><div class="flags">${['S','Z','H','P/V','N','C'].map((f,j)=>`<div><strong>${f}</strong>${esc(i.flags[j])}</div>`).join('')}</div><p class="note">Y/X: ${esc(i.xy)}</p>${i.extra.map(x=>`<p class="note">${esc(x)}</p>`).join('')}<h3>1命令の実行例</h3><pre>${e.bytes.map(b=>hex(b)).join(' ')}
${esc(e.mnemonic)}
実測 ${e.tStates} T-states</pre>${table(['変化した状態','実行前','実行後'],changes.map(k=>[k.toUpperCase(),value(k,e.before[k]),value(k,e.after[k])]))}${e.memory.length?'<h3>メモリ書込み</h3>'+table(['アドレス','前','後'],e.memory.map(m=>[hex(m.address,4),hex(m.before),hex(m.after)])):''}${e.ports.length?'<h3>I/Oアクセス</h3>'+table(['操作','ポート','値'],e.ports.map(p=>[p.operation,hex(p.address,4),hex(p.data)])):''}<details><summary>初期状態と例の条件</summary>${table(['状態','値'],Object.entries(e.before).map(([k,v])=>[k.toUpperCase(),value(k,v)]))}<p class="note">PC=2000h。4000hから81 28 55、9000hから34 12、その他のRAMは0。即値n=42h、nn=4000h、変位d/e=+2。割込み入力なし、周辺機器なし（入力FFh）、ROM保護なしの隔離環境です。副レジスタはCPU初期値0。</p></details><p class="note">この例は候補CPUを1命令実行した説明用の記録であり、外部oracleや全条件の検証結果ではありません。<a href="#sources">根拠と制約</a></p><a href="#reference/${i.id}">この命令へのリンク</a>`;
}
const components={
 cpu:['Z80 CPU','命令・レジスタ・割込み状態を持つ実行主体。16bitアドレス／8bitデータを扱います。実装は命令単位のエミュレーションであり、ピンの電気的動作を再現した回路ではありません。'],
 bus:['Memory / I/O Bus','CPUのメモリ読書きとI/Oを仲介。メモリ空間とI/O空間は別です。ROM overlay、RAM underlay、デバイス振分け、観測用トレースを扱います。'],
 rom:['Pageable firmware · 16 KiB','RESET時はBoot ROM 0000–1FFFhとExtension ROM bank 0 2000–3FFFh。port 00hでbank、shadow write、lower RAMを制御します。'],
 ram:['Physical RAM · 64 KiB','0000–FFFFhに物理RAMがあります。RESET時は下位16 KiBがROMに隠れ、4000–FFFFhが見えます。full-RAM modeでは全域がRAMです。'],
 vram:['Text VRAM · 2,000 bytes','C000–C7CFh。80×25の文字コード。CPUが書いた値を映像側が読みます。専用の別RAMチップやDMAを実装したものではありません。'],
 video:['Text video renderer','VRAMをdebugPeekで非破壊参照し、CG-ROMの8×16ドットをCanvasへ描画。CPUの読出しトレースやT-statesには加算しません。'],
 cgrom:['CG-ROM · 4 KiB','256文字×16バイト。CPUにマップされていない描画器専用データ。文字コード×16+行で参照し、bit7を左端に描きます。'],
 display:['DM-80 display','論理解像度640×400。整数倍率はpixel-perfect、縮小／非整数倍率はgentle AA。走査線とphosphorは表示演出です。DIGITAL_MONOという論理映像系であり、物理DisplayPort規格の端子ではありません。'],
 keyboard:['Keyboard FIFO','ホストのキー入力をASCIIバイトとしてFIFOへ。CPUはINで読み、BIOSがポーリングします。既定容量64バイト。'],
 block:['Virtual Disk A','77 track × 26 sector × 128 byteの媒体を持つPIO block device。CPUはI/O 30h–36hを通して1 sectorずつ読書きします。機械式FDDのseek/rotation timingやDMAではありません。'],
 future:['拡張予定 · 未実装','B: drive、物理FDC、シリアル、プリンタ、物理映像出力は将来候補。IRQ/DMAや端子規格は未確定です。予約RSTがあってもドライバ実装済みではありません。']
};
function system(id){
 const node=(key,x,y,w=240)=>`<a href="#system/${key}" aria-label="${esc(components[key][0])}"><rect class="box" x="${x}" y="${y}" width="${w}" height="64"/><text x="${x+w/2}" y="${y+39}">${{cpu:'Z80 CPU',bus:'MEM / I/O BUS',rom:'BOOT + EXT ROM · 16K',ram:'PHYSICAL RAM · 64K',vram:'VRAM · 80×25',video:'TEXT RENDERER',cgrom:'CG-ROM · 4K',display:'DM-80 · 640×400',keyboard:'KEYBOARD FIFO',block:'VIRTUAL DISK A'}[key]}</text></a>`;
 main.innerHTML=`<article class="article">${title('システム構成','「何がどこにつながるか」を辿る、論理構成図。部品を選ぶと役割を表示します。')}<svg class="diagram" viewBox="0 0 600 820" role="group" aria-labelledby="diagram-title diagram-desc"><title id="diagram-title">SHINO-80 論理接続図</title><desc id="diagram-desc">CPUとBusを中心にROM、RAM、キーボード、Virtual Disk Aが接続。RAM内のVRAMと描画専用CG-ROMを描画器が参照し、DM-80へ出力。</desc><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10Z" fill="#6acbff"/></marker></defs><path class="wire" d="M300 94V140 M300 204V235H160V260 M300 235H440V260 M440 324V380 M180 172H20V412H40 M180 204H20V722H40"/><path class="wire" marker-end="url(#arrow)" d="M440 444V520 M280 552H320 M440 584V650"/>${node('cpu',180,30)}${node('bus',180,140)}${node('rom',40,260)}${node('ram',320,260)}${node('keyboard',40,380)}${node('vram',320,380)}${node('video',320,520)}${node('display',320,650)}${node('cgrom',40,520)}${node('block',40,690)}<text class="label" x="300" y="122">CPU read / write</text><text class="label" x="430" y="482">observer read</text><text class="label" x="430" y="618">logical video</text></svg><div class="legend"><span>現在の論理接続</span></div><p class="note">キーボードとVirtual Disk AはI/O Bus接続です。VRAM→描画器は観測読出し、CG-ROM→描画器は字形参照。概念図の線は物理ピンや回路配線ではありません。</p><div class="component-links">${Object.entries(components).map(([k,v])=>`<a href="#system/${k}">${esc(v[0])}</a>`).join('')}</div><section class="component-detail" aria-live="polite"><h2>${esc((components[id]||components.cpu)[0])}</h2><p>${esc((components[id]||components.cpu)[1])}</p></section><h2>キーを押して文字が出るまで</h2><p>ホスト入力 → Keyboard FIFO → CPUのIN → BIOS/MON → VRAMへの書込み → CG-ROMの字形参照 → Canvas → DM-80表示。</p><p>CG-ROMはCPUと直接つながっていません。Virtual Disk AはCPUのPIOで128 byteずつ転送します。将来ハードウェアへ移すなら、アドレスデコード、VRAMアクセス調停、クロックと映像タイミングなどを別途設計する必要があります。</p></article>`;
}
function maps(){main.innerHTML=`<article class="article">${title('メモリ・I/Oマップ','物理RAMと、CPUから現在見えるoverlayを分けて示します。')}${table(['CPUアドレス','RESET時の可視領域','full-RAM mode'],[['0000–1FFF','Boot / Recovery ROM · 8 KiB','RAM underlay'],['2000–3FFF','Extension ROM · 8 KiB bank 0','RAM underlay'],['4000–BFFF','RAM','RAM'],['C000–C7CF','Text VRAM · 2,000 B','Text VRAM'],['C7D0–DFFF','RAM','RAM'],['E000–E16F','BIOS/MON work area','BIOS/MON work area'],['E170–FFFF','RAM / stack','RAM / stack']])}<p class="note">物理RAMは常に0000–FFFFhの64 KiBです。RESET後は下位16 KiBだけROM overlayに隠れます。debugPeekはCPUから見える値、RAM underlayの直接表示・編集は別操作です。VRAM、作業領域、stackは物理RAM内の用途区分です。CG-ROMはCPUマップ外です。</p><h2>Memory control I/O</h2>${table(['下位port','bit','意味'],[['00h','0 LOW_RAM','1で0000–3FFFhをRAMへ即時切替'],['00h','1 SHADOW_WRITE','ROM表示中のCPU書込みをRAM underlayへ通す'],['00h','2–3','予約。readは0'],['00h','4–7 EXT_BANK','ROM表示中の2000–3FFFh extension bankを選択']])}<p>RESET値は00hです。page-outはOUT命令直後に有効になるため、LOW_RAMを立てるコードは4000h以上のRAMから実行し、その先もRAMに置く必要があります。SHADOW_WRITEは明示的に立てない限り無効で、通常のROM書込みは破棄されます。現行firmwareはbank 0のみを搭載し、未搭載bankのreadはFFhです。</p><h2>Keyboard I/O</h2>${table(['下位ポート','IN','OUT'],[['20h DATA','先頭バイトを取り出す。空なら00h','無視'],['21h STATUS','bit0=ready / bit7=overrun','bit7=1でoverrunだけ解除']])}<p>デバイスは下位8bitで選択するため、0020hもFF20hも同じDATAです。CPUとBusは16bitのI/Oアドレスを保持します。FIFO満杯では新しい入力を捨て、overrunを立てます。STATUS読出しではキューは減りません。</p><pre>DB 21     IN A,(21h) ; ready bit を確認
E6 01     AND 01h
; readyなら
DB 20     IN A,(20h) ; 1文字取り出す</pre><p class="note">IN A,(n)のI/O上位は実行前A。IN r,(C)ではBC全体です。デバイス未割当のI/OはBus内部ラッチ（初期FFh）であり、実在機器のopen-bus再現ではありません。</p><h2>Virtual Disk A I/O</h2>${table(['下位ポート','IN','OUT'],[['30h STATUS','bit0 READY / bit2 DRQ / bit6 WP / bit7 ERROR','無視'],['31h COMMAND','最後のcommand','01h READ / 02h WRITE / 7Fh RESET'],['32h DRIVE','選択drive','0=A:'],['33h TRACK','track','0–76'],['34h SECTOR','sector','1–26'],['35h DATA','READ中の次byte','WRITE中の次byte'],['36h ERROR','0–6','00hでerror clear']])}<p>媒体は77 track × 26 sector × 128 byte、合計${data.machine.blockImageSize.toLocaleString()} byteです。正しいREAD/WRITE commandでDRQが立ち、DATAを128回転送すると自動でidleへ戻ります。debug表示はDATA位置を進めません。WRITEは128 byteが揃うまで媒体へ反映しません。RESET/POWERではcontrollerだけを戻し、挿入中の媒体は保持します。</p><p class="note">v0.1は命令境界でcommandを受理するPIO block deviceです。seek、rotation、WAIT、DMA、割込み、host file保存は未実装です。CP/M/CBIOSもまだ入っていません。</p><div class="notice">B: drive、物理FDC、シリアル、物理映像端子のポートは未割当です。予約値を仕様として創作していません。</div></article>`;}
function bios(){
 const rows=[['PUTCHAR','A=文字','文字出力。CR/LF/BS、折返しとスクロール'],['NEWLINE','なし','次の行へ'],['CLS','なし','画面クリア・カーソル先頭'],['PRINT_STRING','HL=NUL終端文字列','出力後HLは終端NUL位置'],['GETCHAR','なし','ポーリング待ち、A=入力文字'],['GETLINE','HL=buffer、B=上限（NUL除く）','A=長さ、NUL終端。BC/DE/HL保持'],['PRINT_HEX8','A=8bit値','2桁の16進文字。AF保持'],['PRINT_HEX16','HL=16bit値','4桁の16進文字。AF保持'],['PARSE_HEX16','HL=4文字','成功: CF=1、DE=値、HL+=4'],['DISASM_ONE','HL=命令先頭','1行出力。HL=次命令、A=長さ'],['RAM_HANDOFF','HL=4000h以上のentry、A=LOW_RAMを含む制御値','F800h trampolineからROMをpage-out。成功時は戻らない']].map(r=>[hex(data.machine.labels['BIOS_API_'+r[0]],4)+'h',...r]);
 main.innerHTML=`<article class="article">${title('BIOS・MON','ROM上の対話コンソールv0.3と、v0.5 RAM handoff。')}<h2>起動</h2><p>RESET 0000h → IPL 0200h → DI / SP=F000h → 画面初期化 → MONの「*」プロンプト。CPUの割込み機能が揃っていても、このROMが割込み駆動OSになったわけではありません。</p><h2>MONコマンド</h2>${table(['入力してEnter','動作'],[['H または ?','ヘルプ'],['C','画面クリア'],['D 0100','0100hから64バイトを8バイト単位で表示'],['D 0100 017F','両端を含む範囲ダンプ。最大256バイト'],['R','コマンド入力前に保存した主/副レジスタ、IX/IY、SP、I/R'],['U 0100','0100hから8命令を逆アセンブル'],['U 0100 011F','範囲内の命令を逆アセンブル。最大256バイト/32命令'],['B','page zeroを準備し全64 KiB RAMへ移る内蔵boot診断。RESETで復帰']])}<p>大文字・小文字どちらも使用できます。アドレスは厳密に4桁の16進数。範囲はFFFFhから0000hへ回り込めます。上限に達した場合はRANGE LIMITEDを表示します。入力は最大63文字、Backspace/DELで訂正可能。かな漢字ではなくASCIIのコンソールです。</p><div class="notice">BはCP/Mではありません。8000hのoriginal診断payloadへ非復帰handoffし、ROM BIOSを呼ばずVRAMへ成功表示してHALTします。RはGETLINE前のMON診断コンテキストです。UはDD/FD異常列でも必ず前進します。UIのMEMタブとROM内MONは別機能です。</div><h2>BIOS jump table</h2>${table(['CALL先','機能','入力','動作'],rows)}<p>RST 08h（CF）はPUTCHAR、RST 10h（D7）はGETCHAR。呼出し前に有効なRAMスタックを用意します。GETCHAR/GETLINEは入力が来るまで戻りません。RAM_HANDOFFはF800h–F802hを一時使用し、成功時は戻りません。すべてのAPIが全レジスタやFを保持するわけではありません。</p><h3>「A」を表示する最小例</h3><pre>3E 41       LD A,41h
CF          RST 08h
; または CD 00 01  CALL 0100h</pre><h2>予約ベクタ</h2><p>RST18/20はdisk、RST28はserial、RST30はprinter用の予約。0038h（IM1）と0066h（NMI）も予約スタブです。現在は未実装ルーチンへ飛びRETするだけで、正しい割込みサービスやディスクドライバではありません。</p><h2>次の拡張</h2><p>メモリ/レジスタ編集とプログラム実行には、安全にMONへ戻すBREAK/NMI契約が必要です。媒体I/Oはデバイス契約と一緒に設計します。このv0.3ではまだ実装していません。</p></article>`;
}
function draw(canvas,code){canvas.width=8;canvas.height=16;const c=canvas.getContext('2d');c.fillStyle='#06100a';c.fillRect(0,0,8,16);c.fillStyle='#8fffae';for(let y=0;y<16;y++)for(let x=0;x<8;x++)if(data.machine.cgBytes[code*16+y]&(128>>x))c.fillRect(x,y,1,1);}
function cgrom(id){
 const code=/^[0-9A-Fa-f]{2}$/.test(id||'')?parseInt(id,16):0x41;
 main.innerHTML=`<article class="article">${title('CG-ROM atlas','実際の4,096バイトから描く、256文字の字形一覧。文字を選ぶと16行のデータを表示します。')}<div class="glyph-detail"><canvas id="large" aria-label="選択中の文字 ${hex(code)}h"></canvas><div><h2 style="margin-top:0">${hex(code)}h ${code>=32&&code<=126?esc(String.fromCharCode(code)):''}</h2><pre>${Array.from({length:16},(_,y)=>hex(y)+': '+hex(data.machine.cgBytes[code*16+y])+'  '+data.machine.cgBytes[code*16+y].toString(2).padStart(8,'0')).join('\n')}</pre></div></div><div class="glyphs">${Array.from({length:256},(_,n)=>`<button class="glyph" data-code="${n}" aria-label="文字 ${hex(n)}h" aria-pressed="${n===code}"><canvas aria-hidden="true"></canvas><span>${hex(n)}</span></button>`).join('')}</div><h2>データ形式</h2><p>8×16、1行1バイト、bit7が左端。アドレスは文字コード×16+行。ブラウザのフォントには依存しません。この一覧は演出なしのpixel表示です。</p><p class="source-path">SHA-256: ${data.machine.cgHash}<br>CRC32: ${data.machine.cgCRC}</p><p class="note">CG-ROMは描画側専用でCPUのメモリマップ外。DM-80のAA・phosphor・scanlineは字形データそのものとは別です。</p></article>`;
 draw(main.querySelector('#large'),code);main.querySelectorAll('.glyph').forEach(b=>{draw(b.querySelector('canvas'),Number(b.dataset.code));b.onclick=()=>{const scroll=window.scrollY;location.hash='cgrom/'+hex(Number(b.dataset.code));requestAnimationFrame(()=>window.scrollTo(0,scroll));};});
}
function sources(){main.innerHTML=`<article class="article">${title('資料・精度・再生成','実装から採取した情報と、外部の検証根拠を区別します。')}<div class="notice">基準: ${esc(data.baseline)}。mainへリリース済みであることを意味しません。本書v0.1は、その候補を読むための独立HTMLです。</div><h2>作り方</h2><p>命令名・長さ・T-statesはdecoderから採取。日本語の動作・フラグ説明は別の解説データ。実行例は固定した初期状態でCPUを1命令だけ動かしたものです。マップ・字形・BIOS入口は現行ソースに基づきます。ROM内DISASM_ONEも同じdecoderから圧縮表を生成し、CPU上の全1,780標準形照合テストを行います。</p><p>一覧には別名や未使用EDを含む1,780エンコーディングがあります。任意長の接頭辞列を全列挙したものでも、1,780種類の独立した機能でもありません。</p><h2>CPU検証の記録</h2><p>基準候補のPHASE 1J記録: 外部oracle 1,604,000ケース PASS / Failure 0。BASE 252k、CB 256k、ED 80k、DD/FD各252k、DDCB/FDCB各256k。命令一覧の全1780項目に1000ケースずつの外部検証があるという意味ではありません。</p><p>命令単位のNMOS寄りモデルです。WAIT/BUSRQ、電気的競合、完全なピンサイクル再現、CPU個体差、IM0の外部複数バイト命令ストリームは保証対象外。非公式命令やY/X/WZ/P/Qを他の実機へ移植するときは差異に注意してください。</p><h2>一次資料・検証データ</h2><ul><li><a href="https://www.zilog.com/docs/z80/um0080.pdf" target="_blank" rel="noopener">Zilog Z80 CPU User Manual</a> — 公式命令とアーキテクチャ</li><li><a href="https://github.com/hoglet67/Z80Decoder/wiki/Undocumented-Flags" target="_blank" rel="noopener">Z80Decoder: Undocumented Flags</a> — ハードウェア観測に基づく非公式フラグ</li><li><a href="https://github.com/SingleStepTests/z80/tree/ebe1875d48f374bcfd4b505d8eb8ee751568b5f7" target="_blank" rel="noopener">SingleStepTests/z80 · 固定oracle revision</a></li></ul><p class="note">外部リンクを開く場合だけネットワークが必要です。本書の検索・図・字形はオフラインで利用できます。Zilog公式マニュアルの転載ではなく、SHINO-80向けに作成した実装解説です。</p><h2>ソースの指紋</h2>${Object.entries(data.sources).map(([p,h])=>`<p class="source-path"><a href="https://github.com/ssnshino/shinoCPUEmulator/blob/${data.revision}/${p}" target="_blank" rel="noopener">${p}</a><br>SHA-256 ${h}</p>`).join('')}<h2>再生成</h2><pre>npm run build:manual
npm run test:manual</pre><p>src/manual と scripts/build-technical-manual.cjs が正本。deployのHTMLは生成物です。CPU・ROMの機能追加とは独立しています。</p></article>`;}
let previous='';
function route(){
 const [raw,id]=(location.hash.slice(1)||'reference').split('/');const section=['reference','system','map','bios','cgrom','sources'].includes(raw)?raw:'reference';
 document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#'+section)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 if(section==='reference'&&previous==='reference'&&main.querySelector('#detail')){if(data.instructions.some(i=>i.id===id))state.id=id;main.querySelectorAll('.row').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===state.id)));detail();if(innerWidth<=1000&&id)main.querySelector('#detail').scrollIntoView({block:'start'});}
 else ({reference:()=>reference(id),system:()=>system(id),map:maps,bios,cgrom:()=>cgrom(id),sources})[section]();
 if(previous&&previous!==section)window.scrollTo(0,0);
 if(section==='system'&&id){const sectionDetail=main.querySelector('.component-detail');sectionDetail.insertAdjacentHTML('beforeend','<a href="#system">図の先頭へ戻る</a>');sectionDetail.scrollIntoView({block:'start'});}
 else if(section==='system')window.scrollTo(0,0);
 previous=section;
}
window.addEventListener('hashchange',route);route();
})();
