'use strict';
const fs=require('node:fs'),vm=require('node:vm');
const f='deploy/one_page_shino80_v0.0.6_z80_phase1d.html',h=fs.readFileSync(f,'utf8');
for(const m of ['/*__CSS__*/','/*__BUS__*/','/*__FLAGS__*/','/*__DECODER__*/','/*__CPU__*/','/*__APP__*/'])if(h.includes(m))throw Error('unresolved '+m);
if(!h.includes('Z80 CALL / RET STACK ONLINE'))throw Error('phase banner missing');
if(/<script[^>]+src=|<link[^>]+href=/i.test(h))throw Error('external runtime dependency');
if(/\bprompt\s*\(/.test(h))throw Error('browser prompt() must not be used');
[...h.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].forEach((m,i)=>new vm.Script(m[1],{filename:'inline-'+i}));
if(!h.trimEnd().endsWith('</html>'))throw Error('truncated html');
console.log('v0.0.6 artifact static PASS',Buffer.byteLength(h),'bytes');
