'use strict';
const fs=require('node:fs'),vm=require('node:vm');
const f='deploy/one_page_shino80_v0.0.8_phase2a1_power_reset.html',h=fs.readFileSync(f,'utf8');
for(const m of ['/*__CSS__*/','/*__BUS__*/','/*__FLAGS__*/','/*__DECODER__*/','/*__CPU__*/','/*__CGROM__*/','/*__SYSTEM_ROM__*/','/*__VIDEO__*/','/*__APP__*/'])if(h.includes(m))throw Error('unresolved '+m);
for(const id of ['powerBtn','crtCanvas','crtViewport','displayDevice','statusPc','statusR','statusT','statusLast','statusVideo','runPauseBtn','stepBtn','moreMenu'])if(!h.includes(`id="${id}"`))throw Error('missing DOM id '+id);
if(!h.includes('PHASE 2A.1 v0.0.8'))throw Error('phase banner missing');
if(!h.includes('width:100%'))throw Error('full raster canvas CSS missing');
if(!h.includes('DM-80')||!h.includes('SHINOMIYA')||!h.includes('GREEN MONO DIGITAL DISPLAY'))throw Error('display nameplate missing');
if(h.includes('shell-legend'))throw Error('legacy monitor info band must be removed');
if(/<script[^>]+src=|<link[^>]+href=/i.test(h))throw Error('external runtime dependency');
if(/\bprompt\s*\(/.test(h))throw Error('browser prompt() must not be used');
const scripts=[...h.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)];
if(scripts.length!==8)throw Error('inline script count '+scripts.length);
scripts.forEach((m,i)=>new vm.Script(m[1],{filename:'inline-'+i}));
if(!h.trimEnd().endsWith('</html>'))throw Error('truncated html');
console.log('v0.0.8 artifact static PASS',Buffer.byteLength(h),'bytes');
